### ISSUE TITLE
Getting sent 22 byte audio files when trying to use the synthesize command

### ISSUE THREAD

**Issue by LiminalSeraphim** [PiotrDabkowski/discord-bot#2]
I believe I have everything set up properly, because the user info command gives me correct information, but the actual synthesize command always gives me something along the lines of "audio-[6 digit number].mp3" that's unplayable. Not sure what I should upload that would be helpful in figuring out the problem.

**Comment by AllSpaghettiNoCode** [comment]
2 things to ask (this might be obvious, but i need to know for sure):

1: are you on the 'creator' plan,

2: Did you run '/login' first?

if both of these things you did, I'll see if its on my end.

**Comment by LiminalSeraphim** [comment]
Im glad you’re checking that first because I think I don’t have the creator plan lol. Im at work right now but Ill swap plans and see if that resolves the problem. Thank you!

**Comment by AllSpaghettiNoCode** [comment]
no worries, I will be adding a fix for that eventually so its all good 👍
