### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by wilburforce666** [PiotrDabkowski/discord-bot#3]
Traceback (most recent call last):
  File "C:\Users\wilbu\Desktop\discord-bot-main\elevenbot.py", line 2, in <module>
    from loginModal import ModalView
  File "C:\Users\wilbu\Desktop\discord-bot-main\loginModal.py", line 3, in <module>
    class LoginModal(miru.Modal):
AttributeError: module 'miru' has no attribute 'Modal'

I have installed miru etc but still getting this error. is it a python version thing? what python version are you on

**Comment by AllSpaghettiNoCode** [comment]
it requires python 3.8 or 3.8.6. If you're on that version, check which version Hikari and miru are on. 

(Reason why you're getting that error is because the Modal thing wasn't introduced until those python versions came around)
