### ISSUE TITLE
Free Tier usage disabled major bug.

### ISSUE THREAD

**Issue by AllSpaghettiNoCode** [PiotrDabkowski/discord-bot#4]
# Cannot synthesize anything due to attached image.
![image](https://github.com/elevenlabs/discord-bot/assets/79474598/36d468be-79a2-4621-8e2b-5daa51809f0a)
## Cause: Requests was requesting everything from the same IP, and so ElevenLabs limited the free tier due to this.

---

**Comment by Vessel-Legends** [comment]
The synthesize command will be disabled shortly, as is this a bigger issue than I thought. It **will** still be fixed, but it could be a few days.

**Comment by Vessel-Legends** [comment]
**A fix has been found, and is being tested. If said fix works fully, the bot will open up the synthesize command, but slowly.**

**Comment by Vessel-Legends** [comment]
I apologize for the major bug everyone. It should be fully working now, but it will be a bit longer sending the request, not too bad though.

**The synthesize source code will not be updated to include the fix.**

**Comment by AllSpaghettiNoCode** [comment]
It looks like everything is running smoothly, with some minor/major delays in synthesizing audio, but nothing **too** bad. If, for some reason, it *still* errors out, this issue will be reopened.
